<footer id="site-footer" class="site-footer">
    <div class="site-container">
        <div class="cols clearfix">
            <div class="col">
                <h2>Licensed in the following states:</h2>
                <h5>Texas, Oklahoma, Louisana, Kansas, Arkansas, Missouri, and Colorado. </h5>

                <div class="map">
                    <img src="theme/images/tmp/state.png" alt="">
                </div>
            </div>
            <div class="col">
                <div class="logo">
                    <img src="theme/images/tmp/footer-main-icon.png" alt="">
                </div>
                <h2>10200 N I-35, Service Rd.<br>
                    Oklahoma City, Ok 73131 </h2>
                <a href="#">View on Map.  </a>
                <div class="info">
                    <span>Hours Of Opperation:</span>
                    <span>M-F, 7:30-5:30</span>
                </div>
                <div class="info">
                    <span>Phone: (405) 478-8833</span>
                    <span>Fax: (405) 478-0901</span>
                </div>
                <h3>Clearing the way</h3>
                <h4>takes just the <span>right</span> touch.</h4>
                <div class="footer-icons">
                    <img src="theme/images/tmp/footer-icon1.png" alt="">
                </div>
            </div>
        </div>
    </div>
</footer>