<header id="site-header" class="site-header">

    <div class="header-top">
        <div class="form form-search">
            <div class="form-item form-type-text ">
                <label></label>
                <input type="text" placeholder="Search" class="form-text">
            </div>

            <div class="btn-wrap">
                <div class="submit-wrapper">
                    <input class="form-submit" type="submit" value="SEARCH">
                </div>
            </div>
        </div>
        <div class="contacts">
            <p>Get Your <span class="free">FREE</span> Estimate Today.<br><span> or call us at 405.478.8833</span></p>
        </div>
    </div>
    <div class="header-bottom">
        <div class="logo">
            <a href="#">
                <img src="theme/images/logo.png" alt="">
            </a>
        </div>
        <div class="title">
            Demolition Since 1976.
        </div>
      <div class="btn-menu">
        <a href="#">MENU</a>
      </div>
        <nav class="nav">
            <ul class="menu">
                <li><a href="#"> Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Equipment</a></li>
                <li><a href="#"> QUALIFICATIONS</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
</header>